spring:
  application:
    name: genealogy
  profiles:
    active: default

genealogy:
  file-extensions-config:
    allowed-file-extensions: jpg,jpeg,png,bmp

  photo-upload-directory-path:
    people: ${UPLOADS_DIRECTORY_PATH}
