spring:
  application:
    name: the-genealogy-api
  profiles:
    active: default
  graphql:
    graphiql:
      enabled: true
    cors:
      allowed-origins: "*"
  servlet:
    multipart:
      max-file-size: 1048576 # 1MB

the-genealogy-project:
  file-extensions-config:
    allowed-file-extensions: jpg,jpeg,png,bmp

  photo-upload-directory-path:
    people: ${UPLOADS_DIRECTORY_PATH}
